image: node:current-alpine

build:
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - npm install --quiet
        - npm run lint
        - npm run build:prod
    artifacts:
        paths:
            - dist/

deploy_prod:
    stage: deploy
    environment:
        name: production
        url: $FIREBASE_URL
    dependencies:
        - build
    cache:
        policy: pull
        paths:
            - node_modules/
    script:
        - npm run deploy